pipeline:
  synch_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=dev
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t cop-java:${JAVA_VERSION} -f Dockerfile-${JAVA_VERSION} .
    when:
      event: push

  vulnerability-scan:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    dockerfile: Dockerfile-${JAVA_VERSION}
    image_name: cop-java:${JAVA_VERSION}
    local_image: true
    tolerate: low
    fail_on_detection: false
    when:
      branch: master
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - source: QUAY_USERNAME
        target: DOCKER_USERNAME
      - source: QUAY_PASSWORD
        target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-java
    dockerfile: Dockerfile-${JAVA_VERSION}
    tags:
      - ${JAVA_VERSION}
    when:
      event: push
      branch: master

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
      {{/build.deployTo}}
      {{build.link}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]

matrix:
  JAVA_VERSION:
    - openjdk-7
    - openjdk-7-alpine
    - openjdk-8
    - openjdk-8-alpine
